M48
; DRILL file {KiCad 7.0.2} date Thu May 11 00:10:08 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-11T00:10:08+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X114.202Y-89.554
X114.202Y-95.334
T2
X166.751Y-91.313
X166.751Y-99.313
T0
M30
